[package]
name = "azymus"
version = "0.1.0"
authors = ["Nathan Douglas <github@tenesm.us>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"
specs = "0.14.0"
specs-derive = "0.4.0"
tcod = { version = "0.15", features = ["serialization"] }
