[package]
name = "conatus"
version = "0.1.0"
authors = ["Nathan Douglas <github@tenesm.us>"]
edition = "2018"

[dependencies]
azymus = { path = "../azymus" }
log = "0.4"
pretty_env_logger = "0.3"
tcod = { version = "0.15", features = ["serialization"] }
